name: Node.js Package

on:
  push:
    branches:
      - master

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com
          scope: '@solvt-ai'
      - run: npm config set '//npm.pkg.github.com/:_authToken' "${GH_TOKEN}"
      - run: npm install
      - run: npm publish
        env:
          GH_TOKEN: ${{secrets.GH_TOKEN}}
